### PR TITLE
Implementing callbacks for monitored items

### PR DESCRIPTION
**Pull request by digitalshow**
Implementation of callbacks for resolving issue #127 
Please review!

### CODE REVIEW

**Comment by WimPessemier** [comment]
@digitalshow I modified your code so that it becomes compatible with c++98, but I accidentally pushed the changes to your branch. It was my intention to push it to my own fork, so that we could discuss which implementation (either your elegant c++11 code or my inelegant but backwards-compatible c++98 code) ends up in the master branch.
   
Anyway if you want, we can have both implementations, and then depending on some compiler flag we either use your c++11 code or my c++98 modifications. 

Backwards compatibility is important to several users of UAF however, so we can offer c++11 features but not enforce them.

**Comment by digitalshow** [comment]
I see the importance of backwards compatibility. Does your code provide a simple way of registering an instance method as a callback? That was one thing I needed.

**Comment by WimPessemier** [comment]
I've added an example of registering a static method, just as the line you commented out. I hope this suffices?

**Comment by digitalshow** [comment]
That is a way to do it. I used the C++11 way to avoid implementing a new class only for a binding. But yeah, that way we stay compatible. Thank you!

**Comment by WimPessemier** [comment]
Okay thanks! Merged.

**Pull request merged**
